#.yml file for Github/Travis-CI support
language: c++
language: c
language: python

os: 
- linux
- osx

compiler:
- gcc
- gcc-c++

addons:
 apt:
  packages:
   - cmake
   - swig
   - libncurses5-dev 
   - libncursesw5-dev

before_install:
- sudo apt-get update -qq
- sudo apt-get install cmake swig

script:
 - ./lint_test.sh
 - ./build.sh -evtcu

