package:
  name: gnsstk
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0')[1:] }}

source:
  git_rev: {{ environ.get('GIT_COMMIT', 'main') }}
  git_url: https://sgl-git.arlut.utexas.edu/sgl-tks/gnsstk.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - GIT_COMMIT

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - python {{python}}
    - setuptools
    - numpy==1.12.1
    - enum34  # [py<=35]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - enum34  # [py<=35]

test:
  imports:
    - gnsstk

about:
  home: https://sgl-git.arlut.utexas.edu:sgl-tks/gnsstk
  summary: The GNSS Toolkit (GNSSTk)
  description: |
    The GNSS Toolkit (GNSSTk) is an open-source (LGPL) project sponsored by
    the Space and Geophysics Laboratory (SGL).
